# Generated by Django 5.2.4 on 2025-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='file',
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
