# Generated by Django 5.2.4 on 2025-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_uploadedcsv_file_alter_uploadedcsv_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
