# Generated by Django 5.2.4 on 2025-07-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_uploadedcsv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='file',
        ),
    ]
