# Generated by Django 5.2.4 on 2025-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_uploadedcsv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
