# Generated by Django 5.2.4 on 2025-07-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_uploadedcsv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
